version: "2"

services:
  db:
    image: mysql:5.7.25
    environment:
      MYSQL_DATABASE: sample
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - db-mysql:/var/lib/mysql
      - ./mysql:/usr/src

volumes:
  db-mysql:
    driver: local
